// This file was generated by jenkins
// Please don't change this

using UnityEngine;

public class MechVersion
{
    public static string Version  = Application.version;
    public static string FullInfo => "v0.6.1 - Build: 1 - 07/15/2021 22:13:27";
}