// This file was generated by jenkins
// Please don't change this

namespace BuildScripts.Runtime
{
    using BuildScripts.Runtime.ConstantValues;

    [ConstantValue]
    public class GameVersion
    {
        [ConstantValue]
        public static string Version { get; private set; } = "0.6.1";

        [ConstantValue]
        public static int BuildNumber { get; private set; } = 1;

        [ConstantValue]
        public static string FullInfo { get; private set; } = "v0.6.1 - Build: 1 - 07/15/2021 22:13:27";

        [ConstantValue]
        public static string ProjectName { get; private set; } = "default";
    }
}