// This file was generated by jenkins
// Please don't change this
namespace GameFoundation.BuildScripts.Runtime
{
    public class GameVersion
    {
        public static string Version     => "0.6.1";
        public static int    BuildNumber => 1;
        public static string FullInfo    => "v0.6.1 - Build: 1 - 07/15/2021 22:13:27";
        public static string ProjectName => "default";
    }
}