// This file was generated by jenkins
// Please don't change this
public class GameVersion
{
    public static string Version => "0.1.0";
    public static string FullInfo => "v0.1.0 - Build: 1 - 07/15/2021 22:13:27";
}
